version: "3.9"
services:
  db:
    image: postgres:16
    container_name: pricepulse-db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: pp
      POSTGRES_PASSWORD: pp_pass
      POSTGRES_DB: pricepulse
    volumes:
      - pp_pgdata:/var/lib/postgresql/data

volumes:
  pp_pgdata: